package com.ea.nimble.tracking;

public enum SynergyConstants
{
  public static final int EVENT_SYNERGY_CUSTOM = 4;
  public final int value;
  
  static
  {
    EVT_APPSTART_NORMALLY = new SynergyConstants("EVT_APPSTART_NORMALLY", 1, 10000);
    EVT_APPSTART_FROMPUSH = new SynergyConstants("EVT_APPSTART_FROMPUSH", 2, 10001);
    EVT_APPSTART_AFTERINSTALL = new SynergyConstants("EVT_APPSTART_AFTERINSTALL", 3, 10002);
    EVT_APPSTART_AFTERUPGRADE = new SynergyConstants("EVT_APPSTART_AFTERUPGRADE", 4, 10003);
    EVT_APP_SESSION_START = new SynergyConstants("EVT_APP_SESSION_START", 5, 10004);
    EVT_APP_SESSION_TIME = new SynergyConstants("EVT_APP_SESSION_TIME", 6, 10005);
    EVT_APP_RESUME_FROM_PUSH = new SynergyConstants("EVT_APP_RESUME_FROM_PUSH", 7, 10007);
    EVT_APPSTART_FROM_URL = new SynergyConstants("EVT_APPSTART_FROM_URL", 8, 10009);
    EVT_APP_ENTER_FOREGROUND_FROM_URL = new SynergyConstants("EVT_APP_ENTER_FOREGROUND_FROM_URL", 9, 10010);
    EVT_NEW_SESSION_START_SYNERGYID_CHANGE = new SynergyConstants("EVT_NEW_SESSION_START_SYNERGYID_CHANGE", 10, 10012);
    EVT_IDENTITY_MIGRATION = new SynergyConstants("EVT_IDENTITY_MIGRATION", 11, 12000);
    EVT_IDENTITY_LOGIN = new SynergyConstants("EVT_IDENTITY_LOGIN", 12, 12001);
    EVT_IDENTITY_LOGOUT = new SynergyConstants("EVT_IDENTITY_LOGOUT", 13, 12002);
    EVT_IDENTITY_MIGRATION_STARTED = new SynergyConstants("EVT_IDENTITY_MIGRATION_STARTED", 14, 12003);
    EVT_APPEND_NORMALLY = new SynergyConstants("EVT_APPEND_NORMALLY", 15, 20000);
    EVT_APPEND_ABNORMALLY = new SynergyConstants("EVT_APPEND_ABNORMALLY", 16, 20001);
    EVT_APP_INTERRUPTED = new SynergyConstants("EVT_APP_INTERRUPTED", 17, 20002);
    EVT_APP_SESSION_END = new SynergyConstants("EVT_APP_SESSION_END", 18, 20003);
    EVT_APP_ENTER_FOREGROUND_FROM_EBISU = new SynergyConstants("EVT_APP_ENTER_FOREGROUND_FROM_EBISU", 19, 20004);
    EVT_APP_SESSION_START_EMBED = new SynergyConstants("EVT_APP_SESSION_START_EMBED", 20, 20005);
    EVT_EMBED_OTD_UPGRADE = new SynergyConstants("EVT_EMBED_OTD_UPGRADE", 21, 20006);
    EVT_SESSION_END_SYNERGYID_CHANGE = new SynergyConstants("EVT_SESSION_END_SYNERGYID_CHANGE", 22, 20007);
    EVT_USER_SHOWN_PN_OPTIN_PROMPT = new SynergyConstants("EVT_USER_SHOWN_PN_OPTIN_PROMPT", 23, 20008);
    EVT_PN_SHOWN_TO_USER = new SynergyConstants("EVT_PN_SHOWN_TO_USER", 24, 20009);
    EVT_OPT_FULL_PURCHASE = new SynergyConstants("EVT_OPT_FULL_PURCHASE", 25, 30000);
    EVT_MOREGAMES_ENTER = new SynergyConstants("EVT_MOREGAMES_ENTER", 26, 30001);
    EVT_MOREGAMES_CLICKTHROUGH = new SynergyConstants("EVT_MOREGAMES_CLICKTHROUGH", 27, 30002);
    EVT_MOREGAMES_GAMESELECT = new SynergyConstants("EVT_MOREGAMES_GAMESELECT", 28, 30004);
    EVT_MOREGAMES_CATEGORYSELECT = new SynergyConstants("EVT_MOREGAMES_CATEGORYSELECT", 29, 30005);
    EVT_MOREGAMES_OVERLAY_APPEARS = new SynergyConstants("EVT_MOREGAMES_OVERLAY_APPEARS", 30, 30006);
    EVT_MOREGAMES_OVERLAY_BUYCLICK = new SynergyConstants("EVT_MOREGAMES_OVERLAY_BUYCLICK", 31, 30007);
    EVT_ENTER_FULL_GAME_OVERVIEW_SCREEN = new SynergyConstants("EVT_ENTER_FULL_GAME_OVERVIEW_SCREEN", 32, 30008);
    EVT_LITE_ED_GAME_DEMO_START = new SynergyConstants("EVT_LITE_ED_GAME_DEMO_START", 33, 30009);
    EVT_LITE_ED_GAME_DEMO_END = new SynergyConstants("EVT_LITE_ED_GAME_DEMO_END", 34, 30010);
    EVT_MAINMENU_BANNER_CLICK = new SynergyConstants("EVT_MAINMENU_BANNER_CLICK", 35, 30011);
    EVT_MAINMENU_TICKER_CLICK = new SynergyConstants("EVT_MAINMENU_TICKER_CLICK", 36, 30012);
    EVT_INSTORE_BANNER_CLICK = new SynergyConstants("EVT_INSTORE_BANNER_CLICK", 37, 30013);
    EVT_INSTORE_TICKER_CLICK = new SynergyConstants("EVT_INSTORE_TICKER_CLICK", 38, 30014);
    EVT_FEATURED_BANNER_CLICK = new SynergyConstants("EVT_FEATURED_BANNER_CLICK", 39, 30015);
    EVT_MOREGAMES_CLICKTHROUGH_FEATURED = new SynergyConstants("EVT_MOREGAMES_CLICKTHROUGH_FEATURED", 40, 30017);
    EVT_MOREGAMES_CLICKTHROUGH_SIDEBANNER = new SynergyConstants("EVT_MOREGAMES_CLICKTHROUGH_SIDEBANNER", 41, 30018);
    EVT_IPAD_UPSELL_MESSAGE_DISPLAYED = new SynergyConstants("EVT_IPAD_UPSELL_MESSAGE_DISPLAYED", 42, 30019);
    EVT_IPAD_UPSELL_MESSAGE_NOTHANKS_CLICKED = new SynergyConstants("EVT_IPAD_UPSELL_MESSAGE_NOTHANKS_CLICKED", 43, 30020);
    EVT_IPAD_UPSELL_MESSAGE_OK_CLICKED = new SynergyConstants("EVT_IPAD_UPSELL_MESSAGE_OK_CLICKED", 44, 30021);
    EVT_IPAD_UPSELL_MESSAGE_LATER_CLICKED = new SynergyConstants("EVT_IPAD_UPSELL_MESSAGE_LATER_CLICKED", 45, 30022);
    EVT_UPSELL_VIDEO_CLICKED = new SynergyConstants("EVT_UPSELL_VIDEO_CLICKED", 46, 30023);
    EVT_USER_TRACKING_OPTOUT = new SynergyConstants("EVT_USER_TRACKING_OPTOUT", 47, 30024);
    EVT_GAMEPLAY_PROGRESSION_SPGAME_START = new SynergyConstants("EVT_GAMEPLAY_PROGRESSION_SPGAME_START", 48, 30025);
    EVT_GAMEPLAY_PROGRESSION_SPGAME_RESTART = new SynergyConstants("EVT_GAMEPLAY_PROGRESSION_SPGAME_RESTART", 49, 30026);
    EVT_GAMEPLAY_PROGRESSION_SPGAME_SAVE = new SynergyConstants("EVT_GAMEPLAY_PROGRESSION_SPGAME_SAVE", 50, 30027);
    EVT_GAMEPLAY_PROGRESSION_SPGAME_CONTINUE = new SynergyConstants("EVT_GAMEPLAY_PROGRESSION_SPGAME_CONTINUE", 51, 30028);
    EVT_GAMEPLAY_PROGRESSION_SPGAME_QUIT = new SynergyConstants("EVT_GAMEPLAY_PROGRESSION_SPGAME_QUIT", 52, 30029);
    EVT_GAMEPLAY_PROGRESSION_SPGAME_COMPLETE = new SynergyConstants("EVT_GAMEPLAY_PROGRESSION_SPGAME_COMPLETE", 53, 30030);
    EVT_GAMEPLAY_PROGRESSION_SPGAME_TIME_SPENT = new SynergyConstants("EVT_GAMEPLAY_PROGRESSION_SPGAME_TIME_SPENT", 54, 30031);
    EVT_GAMEPLAY_PROGRESSION_SPGAME_SCORE = new SynergyConstants("EVT_GAMEPLAY_PROGRESSION_SPGAME_SCORE", 55, 30032);
    EVT_GAMEPLAY_PROGRESSION_TUTORIAL_SKIP = new SynergyConstants("EVT_GAMEPLAY_PROGRESSION_TUTORIAL_SKIP", 56, 30033);
    EVT_GAMEPLAY_PROGRESSION_TUTORIAL_COMPLETE = new SynergyConstants("EVT_GAMEPLAY_PROGRESSION_TUTORIAL_COMPLETE", 57, 30034);
    EVT_GAMEPLAY_PROGRESSION_CUTSCENE_SKIP = new SynergyConstants("EVT_GAMEPLAY_PROGRESSION_CUTSCENE_SKIP", 58, 30035);
    EVT_GAMEPLAY_PROGRESSION_CONTROLSCHEME_USED = new SynergyConstants("EVT_GAMEPLAY_PROGRESSION_CONTROLSCHEME_USED", 59, 30036);
    EVT_GAMEPLAY_PROGRESSION_CHARACTER = new SynergyConstants("EVT_GAMEPLAY_PROGRESSION_CHARACTER", 60, 30037);
    EVT_GAMEPLAY_PROGRESSION_MPGAME_START = new SynergyConstants("EVT_GAMEPLAY_PROGRESSION_MPGAME_START", 61, 30038);
    EVT_GAMEPLAY_PROGRESSION_MPGAME_QUIT = new SynergyConstants("EVT_GAMEPLAY_PROGRESSION_MPGAME_QUIT", 62, 30039);
    EVT_GAMEPLAY_PROGRESSION_MPGAME_DISCONNECT = new SynergyConstants("EVT_GAMEPLAY_PROGRESSION_MPGAME_DISCONNECT", 63, 30040);
    EVT_GAMEPLAY_PROGRESSION_MPGAME_COMPLETE = new SynergyConstants("EVT_GAMEPLAY_PROGRESSION_MPGAME_COMPLETE", 64, 30041);
    EVT_GAMEPLAY_PROGRESSION_MPGAME_TIME_SPENT = new SynergyConstants("EVT_GAMEPLAY_PROGRESSION_MPGAME_TIME_SPENT", 65, 30042);
    EVT_MULTITASKING_USER_APP_MINIMIZED = new SynergyConstants("EVT_MULTITASKING_USER_APP_MINIMIZED", 66, 30043);
    EVT_MULTITASKING_USER_APP_RESUMED = new SynergyConstants("EVT_MULTITASKING_USER_APP_RESUMED", 67, 30044);
    EVT_MULTITASKING_USER_START_TUTORIAL = new SynergyConstants("EVT_MULTITASKING_USER_START_TUTORIAL", 68, 30045);
    EVT_MTXVIEW_ENTER = new SynergyConstants("EVT_MTXVIEW_ENTER", 69, 40000);
    EVT_MTXVIEW_GAMECATEGORY = new SynergyConstants("EVT_MTXVIEW_GAMECATEGORY", 70, 40001);
    EVT_MTXVIEW_ITEMSELECT = new SynergyConstants("EVT_MTXVIEW_ITEMSELECT", 71, 40002);
    EVT_MTXVIEW_ITEMPURCHASE = new SynergyConstants("EVT_MTXVIEW_ITEMPURCHASE", 72, 40003);
    EVT_MTXVIEW_ENTER_FROMCTX = new SynergyConstants("EVT_MTXVIEW_ENTER_FROMCTX", 73, 40004);
    EVT_MTXVIEW_FREEITEM_DOWNLOADED = new SynergyConstants("EVT_MTXVIEW_FREEITEM_DOWNLOADED", 74, 40005);
    EVT_MTXVIEW_ITEM_PURCHASED = new SynergyConstants("EVT_MTXVIEW_ITEM_PURCHASED", 75, 40006);
    EVT_IAC_MTX_ITEM_USED = new SynergyConstants("EVT_IAC_MTX_ITEM_USED", 76, 40007);
    EVT_MTXVIEW_ITEM_PURCHASED_REFERRERDATA = new SynergyConstants("EVT_MTXVIEW_ITEM_PURCHASED_REFERRERDATA", 77, 40008);
    EVT_MTXVIEW_ITEMPURCHASE_SLOTDATA = new SynergyConstants("EVT_MTXVIEW_ITEMPURCHASE_SLOTDATA", 78, 40009);
    EVT_MTXVIEW_ITEDISPLAYED = new SynergyConstants("EVT_MTXVIEW_ITEDISPLAYED", 79, 40010);
    EVT_IGE_FREE_CREDITS_EARNED = new SynergyConstants("EVT_IGE_FREE_CREDITS_EARNED", 80, 40011);
    EVT_IGE_PAID_CREDITS_EARNED = new SynergyConstants("EVT_IGE_PAID_CREDITS_EARNED", 81, 40012);
    EVT_IGE_GIFT_RECEIVED = new SynergyConstants("EVT_IGE_GIFT_RECEIVED", 82, 40013);
    EVT_IGE_GIFT_SENT = new SynergyConstants("EVT_IGE_GIFT_SENT", 83, 40014);
    EVT_IGE_FREE_CREDITS_ITEMS_CLICK = new SynergyConstants("EVT_IGE_FREE_CREDITS_ITEMS_CLICK", 84, 40015);
    EVT_IGE_PAID_CREDITS_ITEMS_CLICK = new SynergyConstants("EVT_IGE_PAID_CREDITS_ITEMS_CLICK", 85, 40016);
    EVT_IGE_STORE_VISIT = new SynergyConstants("EVT_IGE_STORE_VISIT", 86, 40017);
    EVT_IGE_PAID_CREDITS_PURCHASE_REVENUE = new SynergyConstants("EVT_IGE_PAID_CREDITS_PURCHASE_REVENUE", 87, 40018);
    EVT_IGE_PAID_CREDITS_PURCHASE_LEVEL = new SynergyConstants("EVT_IGE_PAID_CREDITS_PURCHASE_LEVEL", 88, 40019);
    EVT_IGE_FREE_CREDITS_PURCHASE_REVENUE = new SynergyConstants("EVT_IGE_FREE_CREDITS_PURCHASE_REVENUE", 89, 40020);
    EVT_IGE_FREE_CREDITS_PURCHASE_LEVEL = new SynergyConstants("EVT_IGE_FREE_CREDITS_PURCHASE_LEVEL", 90, 40021);
    EVT_IGE_GAME_START_CASH_DETAIL = new SynergyConstants("EVT_IGE_GAME_START_CASH_DETAIL", 91, 40022);
    EVT_OFFERWALL_ITEM_REDEEMED_STORE_EAL = new SynergyConstants("EVT_OFFERWALL_ITEM_REDEEMED_STORE_EAL", 92, 40023);
    EVT_OFFERWALL_ITEM_REDEEMED_USER_LEVEL_EAL = new SynergyConstants("EVT_OFFERWALL_ITEM_REDEEMED_USER_LEVEL_EAL", 93, 40024);
    EVT_OFFERWALL_ITEM_CLICK_EAL = new SynergyConstants("EVT_OFFERWALL_ITEM_CLICK_EAL", 94, 40025);
    EVT_OFFERWALL_STORE_VISIT_EAL = new SynergyConstants("EVT_OFFERWALL_STORE_VISIT_EAL", 95, 40026);
    EVT_INGAME_AD_CLICK = new SynergyConstants("EVT_INGAME_AD_CLICK", 96, 40027);
    EVT_INGAME_LEVEL_FREE_CREDITS_COUNT = new SynergyConstants("EVT_INGAME_LEVEL_FREE_CREDITS_COUNT", 97, 40028);
    EVT_INGAME_LEVEL_PAID_CREDITS_COUNT = new SynergyConstants("EVT_INGAME_LEVEL_PAID_CREDITS_COUNT", 98, 40029);
    EVT_USER_LEVEL_MTX_ITEM_PURCHASED = new SynergyConstants("EVT_USER_LEVEL_MTX_ITEM_PURCHASED", 99, 40030);
    EVT_IGE_GAME_START_FREE_CREDIT = new SynergyConstants("EVT_IGE_GAME_START_FREE_CREDIT", 100, 40031);
    EVT_IGE_GAME_START_PAID_CREDIT = new SynergyConstants("EVT_IGE_GAME_START_PAID_CREDIT", 101, 40032);
    EVT_INGAME_EMAIL_OPEN = new SynergyConstants("EVT_INGAME_EMAIL_OPEN", 102, 50001);
    EVT_INGAME_EMAIL_SEND = new SynergyConstants("EVT_INGAME_EMAIL_SEND", 103, 50002);
    EVT_INGAME_EMAIL_RECEIEVE = new SynergyConstants("EVT_INGAME_EMAIL_RECEIEVE", 104, 50003);
    EVT_MEDIAPICKER_OPEN = new SynergyConstants("EVT_MEDIAPICKER_OPEN", 105, 50004);
    EVT_ACCESS_BT_MENU = new SynergyConstants("EVT_ACCESS_BT_MENU", 106, 50005);
    EVT_BEGIN_BT_SESSION = new SynergyConstants("EVT_BEGIN_BT_SESSION", 107, 50006);
    EVT_COMPLETE_BT_SESSION = new SynergyConstants("EVT_COMPLETE_BT_SESSION", 108, 50007);
    EVT_ACCESS_WIFI_MENU = new SynergyConstants("EVT_ACCESS_WIFI_MENU", 109, 50008);
    EVT_BEGIN_WIFI_SESSION = new SynergyConstants("EVT_BEGIN_WIFI_SESSION", 110, 50009);
    EVT_COMPLETE_WIFI_SESSION = new SynergyConstants("EVT_COMPLETE_WIFI_SESSION", 111, 50010);
    EVT_USR_ISSUE_PUSH_NOTIFICATION_CHALLENGE = new SynergyConstants("EVT_USR_ISSUE_PUSH_NOTIFICATION_CHALLENGE", 112, 50011);
    EVT_LANGUAGE_SELECTED = new SynergyConstants("EVT_LANGUAGE_SELECTED", 113, 50012);
    EVT_MENU_PROGRESSION_MAINMENU_SELECTED = new SynergyConstants("EVT_MENU_PROGRESSION_MAINMENU_SELECTED", 114, 50013);
    EVT_MENU_PROGRESSION_MAINMENU_SUBMENU_SELECTED = new SynergyConstants("EVT_MENU_PROGRESSION_MAINMENU_SUBMENU_SELECTED", 115, 50014);
    EVT_MENU_PROGRESSION_GAMEMENU_SELECTED = new SynergyConstants("EVT_MENU_PROGRESSION_GAMEMENU_SELECTED", 116, 50015);
    EVT_MENU_PROGRESSION_GAMEMENU_SUBMENU_SELECTED = new SynergyConstants("EVT_MENU_PROGRESSION_GAMEMENU_SUBMENU_SELECTED", 117, 50016);
    EVT_DEVICE_ORIENTATION_CHANGED = new SynergyConstants("EVT_DEVICE_ORIENTATION_CHANGED", 118, 50017);
    EVT_ERROR_BLUETOOTH_WIFI_BOTH_ACTIVE = new SynergyConstants("EVT_ERROR_BLUETOOTH_WIFI_BOTH_ACTIVE", 119, 50018);
    EVT_ACCESS_INGAME_SCREEN = new SynergyConstants("EVT_ACCESS_INGAME_SCREEN", 120, 60001);
    EVT_LEAVE_INGAME_SCREEN = new SynergyConstants("EVT_LEAVE_INGAME_SCREEN", 121, 60002);
    EVT_USER_GAMEPLAY_FUNNEL_EAL = new SynergyConstants("EVT_USER_GAMEPLAY_FUNNEL_EAL", 122, 60003);
    EVT_USER_TUTORIAL_FUNNEL_EAL = new SynergyConstants("EVT_USER_TUTORIAL_FUNNEL_EAL", 123, 60004);
    EVT_USER_TRANSACTION_FUNNEL = new SynergyConstants("EVT_USER_TRANSACTION_FUNNEL", 124, 60005);
    EVT_USER_MESSAGING_FUNNEL = new SynergyConstants("EVT_USER_MESSAGING_FUNNEL", 125, 60006);
    EVT_USER_SIGNUP_FUNNEL = new SynergyConstants("EVT_USER_SIGNUP_FUNNEL", 126, 60007);
    EVT_USER_GAME_LOAD_FUNNEL = new SynergyConstants("EVT_USER_GAME_LOAD_FUNNEL", 127, 60008);
    EVT_USER_GAME_DOWNLOAD_FUNNEL = new SynergyConstants("EVT_USER_GAME_DOWNLOAD_FUNNEL", 128, 60009);
    EVT_EVENTS_PURGED = new SynergyConstants("EVT_EVENTS_PURGED", 129, 70000);
    EVT_GP_LEVEL_PROMOTION_DAYS_TOTAL_EAL = new SynergyConstants("EVT_GP_LEVEL_PROMOTION_DAYS_TOTAL_EAL", 130, 70005);
    EVT_GP_LEVEL_PROMOTION_GAMEPLAY_TIME_TOTAL_EAL = new SynergyConstants("EVT_GP_LEVEL_PROMOTION_GAMEPLAY_TIME_TOTAL_EAL", 131, 70006);
    EVT_GP_ACHIEVEMENTS_CHECKPOINTS_EAL = new SynergyConstants("EVT_GP_ACHIEVEMENTS_CHECKPOINTS_EAL", 132, 70007);
    EVT_GP_XPGAIN_EVENT_EAL = new SynergyConstants("EVT_GP_XPGAIN_EVENT_EAL", 133, 70008);
    EVT_GP_EVENT_USER_EAL = new SynergyConstants("EVT_GP_EVENT_USER_EAL", 134, 70009);
    EVT_GP_APP_START_USER_LEVEL_EAL = new SynergyConstants("EVT_GP_APP_START_USER_LEVEL_EAL", 135, 70010);
    EVT_EBISU_EMAIL_PROMPT = new SynergyConstants("EVT_EBISU_EMAIL_PROMPT", 136, 80032);
    EVT_EBISU_PROMPT_INPUT = new SynergyConstants("EVT_EBISU_PROMPT_INPUT", 137, 80033);
    EVT_EBISU_REGISTRATION_FUNNEL = new SynergyConstants("EVT_EBISU_REGISTRATION_FUNNEL", 138, 80034);
    EVT_EBISU_OPTIONAL_REGISTRATION_FIELDS = new SynergyConstants("EVT_EBISU_OPTIONAL_REGISTRATION_FIELDS", 139, 80035);
    EVT_EBISU_REGISTRATION_ERROR = new SynergyConstants("EVT_EBISU_REGISTRATION_ERROR", 140, 80036);
    EVT_EBISU_SIGNIN_FUNNEL = new SynergyConstants("EVT_EBISU_SIGNIN_FUNNEL", 141, 80037);
    EVT_EBISU_SIGNIN_ERROR = new SynergyConstants("EVT_EBISU_SIGNIN_ERROR", 142, 80038);
    EVT_EBISU_USER_SIGNIN = new SynergyConstants("EVT_EBISU_USER_SIGNIN", 143, 80039);
    EVT_EBISU_USER_FRIENDS_COUNT = new SynergyConstants("EVT_EBISU_USER_FRIENDS_COUNT", 144, 80040);
    EVT_EBISU_ENTER_EBISUUI = new SynergyConstants("EVT_EBISU_ENTER_EBISUUI", 145, 80041);
    EVT_EBISU_FRIENDS_VISIT = new SynergyConstants("EVT_EBISU_FRIENDS_VISIT", 146, 80042);
    EVT_EBISU_FRIEND_SEARCH = new SynergyConstants("EVT_EBISU_FRIEND_SEARCH", 147, 80043);
    EVT_EBISU_FRIEND_INVITE_SENT = new SynergyConstants("EVT_EBISU_FRIEND_INVITE_SENT", 148, 80044);
    EVT_EBISU_FRIEND_INVITE_ACCPTED = new SynergyConstants("EVT_EBISU_FRIEND_INVITE_ACCPTED", 149, 80045);
    EVT_EBISU_NEWSFEED_VISIT = new SynergyConstants("EVT_EBISU_NEWSFEED_VISIT", 150, 80046);
    EVT_EBISU_NEWSFEED_TILE_BUTTON_CLICK = new SynergyConstants("EVT_EBISU_NEWSFEED_TILE_BUTTON_CLICK", 151, 80047);
    EVT_EBISU_NEWSFEED_BANNER_CLICK = new SynergyConstants("EVT_EBISU_NEWSFEED_BANNER_CLICK", 152, 80048);
    EVT_EBISU_NEWSFEED_UPDATES = new SynergyConstants("EVT_EBISU_NEWSFEED_UPDATES", 153, 80049);
    EVT_EBISU_PROFILE_VISIT = new SynergyConstants("EVT_EBISU_PROFILE_VISIT", 154, 80050);
    EVT_EBISU_LOGO_YES_CLICK = new SynergyConstants("EVT_EBISU_LOGO_YES_CLICK", 155, 80051);
    EVT_EBISU_LOGO_NO_CLICK = new SynergyConstants("EVT_EBISU_LOGO_NO_CLICK", 156, 80052);
    EVT_EBISU_RECOVER_PASSWORD_FUNNEL = new SynergyConstants("EVT_EBISU_RECOVER_PASSWORD_FUNNEL", 157, 80053);
    EVT_EBISU_USER_SIGNOUT = new SynergyConstants("EVT_EBISU_USER_SIGNOUT", 158, 80054);
    EVT_EBISU_LOAD_FAIL = new SynergyConstants("EVT_EBISU_LOAD_FAIL", 159, 80055);
    EVT_EBISU_FRIEND_PROFILE_BANNER_CLICK = new SynergyConstants("EVT_EBISU_FRIEND_PROFILE_BANNER_CLICK", 160, 80056);
    EVT_EBISU_FRIEND_PROFILE_GAME_ICON_CLICK = new SynergyConstants("EVT_EBISU_FRIEND_PROFILE_GAME_ICON_CLICK", 161, 80057);
    EVT_EBISU_FRIEND_INVITE_REJECTED = new SynergyConstants("EVT_EBISU_FRIEND_INVITE_REJECTED", 162, 80058);
    EVT_EBISU_PROFILE_BANNER_CLICK = new SynergyConstants("EVT_EBISU_PROFILE_BANNER_CLICK", 163, 80059);
    EVT_EBISU_PROFILE_GAME_ICON_CLICK = new SynergyConstants("EVT_EBISU_PROFILE_GAME_ICON_CLICK", 164, 80060);
    EVT_GAME_ERROR_CONNECTIVITY = new SynergyConstants("EVT_GAME_ERROR_CONNECTIVITY", 165, 90000);
    EVT_GAME_ERROR_GAMEPLAY = new SynergyConstants("EVT_GAME_ERROR_GAMEPLAY", 166, 90001);
    EVT_KEYTYPE_NONE = new SynergyConstants("EVT_KEYTYPE_NONE", 167, 0);
    EVT_KEYTYPE_GAME_SELLID = new SynergyConstants("EVT_KEYTYPE_GAME_SELLID", 168, 1);
    EVT_KEYTYPE_MTX_SELLID = new SynergyConstants("EVT_KEYTYPE_MTX_SELLID", 169, 2);
    EVT_KEYTYPE_MTX_CATEGORY = new SynergyConstants("EVT_KEYTYPE_MTX_CATEGORY", 170, 3);
    EVT_KEYTYPE_SCREEN_NAME = new SynergyConstants("EVT_KEYTYPE_SCREEN_NAME", 171, 4);
    EVT_KEYTYPE_EVENT_COUNT = new SynergyConstants("EVT_KEYTYPE_EVENT_COUNT", 172, 5);
    EVT_KEYTYPE_DURATION = new SynergyConstants("EVT_KEYTYPE_DURATION", 173, 7);
    EVT_KEYTYPE_FREQUENCY = new SynergyConstants("EVT_KEYTYPE_FREQUENCY", 174, 8);
    EVT_KEYTYPE_FEATURED = new SynergyConstants("EVT_KEYTYPE_FEATURED", 175, 10);
    EVT_KEYTYPE_DMG_SECTION = new SynergyConstants("EVT_KEYTYPE_DMG_SECTION", 176, 11);
    EVT_KEYTYPE_GAME_PRODUCTID = new SynergyConstants("EVT_KEYTYPE_GAME_PRODUCTID", 177, 12);
    EVT_KEYTYPE_DMG_CATEGORY = new SynergyConstants("EVT_KEYTYPE_DMG_CATEGORY", 178, 13);
    EVT_KEYTYPE_SCORE = new SynergyConstants("EVT_KEYTYPE_SCORE", 179, 14);
    EVT_KEYTYPE_ENUMERATION = new SynergyConstants("EVT_KEYTYPE_ENUMERATION", 180, 15);
    EVT_KEYTYPE_TICKERID = new SynergyConstants("EVT_KEYTYPE_TICKERID", 181, 16);
    EVT_KEYTYPE_BANNERID = new SynergyConstants("EVT_KEYTYPE_BANNERID", 182, 17);
    EVT_KEYTYPE_MESSAGEID = new SynergyConstants("EVT_KEYTYPE_MESSAGEID", 183, 18);
    EVT_KEYTYPE_BANNER_POSITION = new SynergyConstants("EVT_KEYTYPE_BANNER_POSITION", 184, 19);
    EVT_KEYTYPE_LANGUAGE = new SynergyConstants("EVT_KEYTYPE_LANGUAGE", 185, 20);
    EVT_KEYTYPE_USER_LEVEL_DATA = new SynergyConstants("EVT_KEYTYPE_USER_LEVEL_DATA", 186, 21);
    EVT_KEYTYPE_FIELD_ID = new SynergyConstants("EVT_KEYTYPE_FIELD_ID", 187, 22);
    EVT_KEYTYPE_LOGO_MESSAGE_ID = new SynergyConstants("EVT_KEYTYPE_LOGO_MESSAGE_ID", 188, 23);
    EVT_KEYTYPE_FIELD_TYPE = new SynergyConstants("EVT_KEYTYPE_FIELD_TYPE", 189, 24);
    EVT_KEYTYPE_SYNERGYID = new SynergyConstants("EVT_KEYTYPE_SYNERGYID", 190, 25);
    EVT_KEYTYPE_JSON_MAP = new SynergyConstants("EVT_KEYTYPE_JSON_MAP", 191, 26);
    EVT_KEYTYPE_LAST_ENUM = new SynergyConstants("EVT_KEYTYPE_LAST_ENUM", 192, 27);
    SynergyConstants[] arrayOfSynergyConstants = new SynergyConstants['Á'];
    arrayOfSynergyConstants[0] = EVT_UNDEFINED;
    arrayOfSynergyConstants[1] = EVT_APPSTART_NORMALLY;
    arrayOfSynergyConstants[2] = EVT_APPSTART_FROMPUSH;
    arrayOfSynergyConstants[3] = EVT_APPSTART_AFTERINSTALL;
    arrayOfSynergyConstants[4] = EVT_APPSTART_AFTERUPGRADE;
    arrayOfSynergyConstants[5] = EVT_APP_SESSION_START;
    arrayOfSynergyConstants[6] = EVT_APP_SESSION_TIME;
    arrayOfSynergyConstants[7] = EVT_APP_RESUME_FROM_PUSH;
    arrayOfSynergyConstants[8] = EVT_APPSTART_FROM_URL;
    arrayOfSynergyConstants[9] = EVT_APP_ENTER_FOREGROUND_FROM_URL;
    arrayOfSynergyConstants[10] = EVT_NEW_SESSION_START_SYNERGYID_CHANGE;
    arrayOfSynergyConstants[11] = EVT_IDENTITY_MIGRATION;
    arrayOfSynergyConstants[12] = EVT_IDENTITY_LOGIN;
    arrayOfSynergyConstants[13] = EVT_IDENTITY_LOGOUT;
    arrayOfSynergyConstants[14] = EVT_IDENTITY_MIGRATION_STARTED;
    arrayOfSynergyConstants[15] = EVT_APPEND_NORMALLY;
    arrayOfSynergyConstants[16] = EVT_APPEND_ABNORMALLY;
    arrayOfSynergyConstants[17] = EVT_APP_INTERRUPTED;
    arrayOfSynergyConstants[18] = EVT_APP_SESSION_END;
    arrayOfSynergyConstants[19] = EVT_APP_ENTER_FOREGROUND_FROM_EBISU;
    arrayOfSynergyConstants[20] = EVT_APP_SESSION_START_EMBED;
    arrayOfSynergyConstants[21] = EVT_EMBED_OTD_UPGRADE;
    arrayOfSynergyConstants[22] = EVT_SESSION_END_SYNERGYID_CHANGE;
    arrayOfSynergyConstants[23] = EVT_USER_SHOWN_PN_OPTIN_PROMPT;
    arrayOfSynergyConstants[24] = EVT_PN_SHOWN_TO_USER;
    arrayOfSynergyConstants[25] = EVT_OPT_FULL_PURCHASE;
    arrayOfSynergyConstants[26] = EVT_MOREGAMES_ENTER;
    arrayOfSynergyConstants[27] = EVT_MOREGAMES_CLICKTHROUGH;
    arrayOfSynergyConstants[28] = EVT_MOREGAMES_GAMESELECT;
    arrayOfSynergyConstants[29] = EVT_MOREGAMES_CATEGORYSELECT;
    arrayOfSynergyConstants[30] = EVT_MOREGAMES_OVERLAY_APPEARS;
    arrayOfSynergyConstants[31] = EVT_MOREGAMES_OVERLAY_BUYCLICK;
    arrayOfSynergyConstants[32] = EVT_ENTER_FULL_GAME_OVERVIEW_SCREEN;
    arrayOfSynergyConstants[33] = EVT_LITE_ED_GAME_DEMO_START;
    arrayOfSynergyConstants[34] = EVT_LITE_ED_GAME_DEMO_END;
    arrayOfSynergyConstants[35] = EVT_MAINMENU_BANNER_CLICK;
    arrayOfSynergyConstants[36] = EVT_MAINMENU_TICKER_CLICK;
    arrayOfSynergyConstants[37] = EVT_INSTORE_BANNER_CLICK;
    arrayOfSynergyConstants[38] = EVT_INSTORE_TICKER_CLICK;
    arrayOfSynergyConstants[39] = EVT_FEATURED_BANNER_CLICK;
    arrayOfSynergyConstants[40] = EVT_MOREGAMES_CLICKTHROUGH_FEATURED;
    arrayOfSynergyConstants[41] = EVT_MOREGAMES_CLICKTHROUGH_SIDEBANNER;
    arrayOfSynergyConstants[42] = EVT_IPAD_UPSELL_MESSAGE_DISPLAYED;
    arrayOfSynergyConstants[43] = EVT_IPAD_UPSELL_MESSAGE_NOTHANKS_CLICKED;
    arrayOfSynergyConstants[44] = EVT_IPAD_UPSELL_MESSAGE_OK_CLICKED;
    arrayOfSynergyConstants[45] = EVT_IPAD_UPSELL_MESSAGE_LATER_CLICKED;
    arrayOfSynergyConstants[46] = EVT_UPSELL_VIDEO_CLICKED;
    arrayOfSynergyConstants[47] = EVT_USER_TRACKING_OPTOUT;
    arrayOfSynergyConstants[48] = EVT_GAMEPLAY_PROGRESSION_SPGAME_START;
    arrayOfSynergyConstants[49] = EVT_GAMEPLAY_PROGRESSION_SPGAME_RESTART;
    arrayOfSynergyConstants[50] = EVT_GAMEPLAY_PROGRESSION_SPGAME_SAVE;
    arrayOfSynergyConstants[51] = EVT_GAMEPLAY_PROGRESSION_SPGAME_CONTINUE;
    arrayOfSynergyConstants[52] = EVT_GAMEPLAY_PROGRESSION_SPGAME_QUIT;
    arrayOfSynergyConstants[53] = EVT_GAMEPLAY_PROGRESSION_SPGAME_COMPLETE;
    arrayOfSynergyConstants[54] = EVT_GAMEPLAY_PROGRESSION_SPGAME_TIME_SPENT;
    arrayOfSynergyConstants[55] = EVT_GAMEPLAY_PROGRESSION_SPGAME_SCORE;
    arrayOfSynergyConstants[56] = EVT_GAMEPLAY_PROGRESSION_TUTORIAL_SKIP;
    arrayOfSynergyConstants[57] = EVT_GAMEPLAY_PROGRESSION_TUTORIAL_COMPLETE;
    arrayOfSynergyConstants[58] = EVT_GAMEPLAY_PROGRESSION_CUTSCENE_SKIP;
    arrayOfSynergyConstants[59] = EVT_GAMEPLAY_PROGRESSION_CONTROLSCHEME_USED;
    arrayOfSynergyConstants[60] = EVT_GAMEPLAY_PROGRESSION_CHARACTER;
    arrayOfSynergyConstants[61] = EVT_GAMEPLAY_PROGRESSION_MPGAME_START;
    arrayOfSynergyConstants[62] = EVT_GAMEPLAY_PROGRESSION_MPGAME_QUIT;
    arrayOfSynergyConstants[63] = EVT_GAMEPLAY_PROGRESSION_MPGAME_DISCONNECT;
    arrayOfSynergyConstants[64] = EVT_GAMEPLAY_PROGRESSION_MPGAME_COMPLETE;
    arrayOfSynergyConstants[65] = EVT_GAMEPLAY_PROGRESSION_MPGAME_TIME_SPENT;
    arrayOfSynergyConstants[66] = EVT_MULTITASKING_USER_APP_MINIMIZED;
    arrayOfSynergyConstants[67] = EVT_MULTITASKING_USER_APP_RESUMED;
    arrayOfSynergyConstants[68] = EVT_MULTITASKING_USER_START_TUTORIAL;
    arrayOfSynergyConstants[69] = EVT_MTXVIEW_ENTER;
    arrayOfSynergyConstants[70] = EVT_MTXVIEW_GAMECATEGORY;
    arrayOfSynergyConstants[71] = EVT_MTXVIEW_ITEMSELECT;
    arrayOfSynergyConstants[72] = EVT_MTXVIEW_ITEMPURCHASE;
    arrayOfSynergyConstants[73] = EVT_MTXVIEW_ENTER_FROMCTX;
    arrayOfSynergyConstants[74] = EVT_MTXVIEW_FREEITEM_DOWNLOADED;
    arrayOfSynergyConstants[75] = EVT_MTXVIEW_ITEM_PURCHASED;
    arrayOfSynergyConstants[76] = EVT_IAC_MTX_ITEM_USED;
    arrayOfSynergyConstants[77] = EVT_MTXVIEW_ITEM_PURCHASED_REFERRERDATA;
    arrayOfSynergyConstants[78] = EVT_MTXVIEW_ITEMPURCHASE_SLOTDATA;
    arrayOfSynergyConstants[79] = EVT_MTXVIEW_ITEDISPLAYED;
    arrayOfSynergyConstants[80] = EVT_IGE_FREE_CREDITS_EARNED;
    arrayOfSynergyConstants[81] = EVT_IGE_PAID_CREDITS_EARNED;
    arrayOfSynergyConstants[82] = EVT_IGE_GIFT_RECEIVED;
    arrayOfSynergyConstants[83] = EVT_IGE_GIFT_SENT;
    arrayOfSynergyConstants[84] = EVT_IGE_FREE_CREDITS_ITEMS_CLICK;
    arrayOfSynergyConstants[85] = EVT_IGE_PAID_CREDITS_ITEMS_CLICK;
    arrayOfSynergyConstants[86] = EVT_IGE_STORE_VISIT;
    arrayOfSynergyConstants[87] = EVT_IGE_PAID_CREDITS_PURCHASE_REVENUE;
    arrayOfSynergyConstants[88] = EVT_IGE_PAID_CREDITS_PURCHASE_LEVEL;
    arrayOfSynergyConstants[89] = EVT_IGE_FREE_CREDITS_PURCHASE_REVENUE;
    arrayOfSynergyConstants[90] = EVT_IGE_FREE_CREDITS_PURCHASE_LEVEL;
    arrayOfSynergyConstants[91] = EVT_IGE_GAME_START_CASH_DETAIL;
    arrayOfSynergyConstants[92] = EVT_OFFERWALL_ITEM_REDEEMED_STORE_EAL;
    arrayOfSynergyConstants[93] = EVT_OFFERWALL_ITEM_REDEEMED_USER_LEVEL_EAL;
    arrayOfSynergyConstants[94] = EVT_OFFERWALL_ITEM_CLICK_EAL;
    arrayOfSynergyConstants[95] = EVT_OFFERWALL_STORE_VISIT_EAL;
    arrayOfSynergyConstants[96] = EVT_INGAME_AD_CLICK;
    arrayOfSynergyConstants[97] = EVT_INGAME_LEVEL_FREE_CREDITS_COUNT;
    arrayOfSynergyConstants[98] = EVT_INGAME_LEVEL_PAID_CREDITS_COUNT;
    arrayOfSynergyConstants[99] = EVT_USER_LEVEL_MTX_ITEM_PURCHASED;
    arrayOfSynergyConstants[100] = EVT_IGE_GAME_START_FREE_CREDIT;
    arrayOfSynergyConstants[101] = EVT_IGE_GAME_START_PAID_CREDIT;
    arrayOfSynergyConstants[102] = EVT_INGAME_EMAIL_OPEN;
    arrayOfSynergyConstants[103] = EVT_INGAME_EMAIL_SEND;
    arrayOfSynergyConstants[104] = EVT_INGAME_EMAIL_RECEIEVE;
    arrayOfSynergyConstants[105] = EVT_MEDIAPICKER_OPEN;
    arrayOfSynergyConstants[106] = EVT_ACCESS_BT_MENU;
    arrayOfSynergyConstants[107] = EVT_BEGIN_BT_SESSION;
    arrayOfSynergyConstants[108] = EVT_COMPLETE_BT_SESSION;
    arrayOfSynergyConstants[109] = EVT_ACCESS_WIFI_MENU;
    arrayOfSynergyConstants[110] = EVT_BEGIN_WIFI_SESSION;
    arrayOfSynergyConstants[111] = EVT_COMPLETE_WIFI_SESSION;
    arrayOfSynergyConstants[112] = EVT_USR_ISSUE_PUSH_NOTIFICATION_CHALLENGE;
    arrayOfSynergyConstants[113] = EVT_LANGUAGE_SELECTED;
    arrayOfSynergyConstants[114] = EVT_MENU_PROGRESSION_MAINMENU_SELECTED;
    arrayOfSynergyConstants[115] = EVT_MENU_PROGRESSION_MAINMENU_SUBMENU_SELECTED;
    arrayOfSynergyConstants[116] = EVT_MENU_PROGRESSION_GAMEMENU_SELECTED;
    arrayOfSynergyConstants[117] = EVT_MENU_PROGRESSION_GAMEMENU_SUBMENU_SELECTED;
    arrayOfSynergyConstants[118] = EVT_DEVICE_ORIENTATION_CHANGED;
    arrayOfSynergyConstants[119] = EVT_ERROR_BLUETOOTH_WIFI_BOTH_ACTIVE;
    arrayOfSynergyConstants[120] = EVT_ACCESS_INGAME_SCREEN;
    arrayOfSynergyConstants[121] = EVT_LEAVE_INGAME_SCREEN;
    arrayOfSynergyConstants[122] = EVT_USER_GAMEPLAY_FUNNEL_EAL;
    arrayOfSynergyConstants[123] = EVT_USER_TUTORIAL_FUNNEL_EAL;
    arrayOfSynergyConstants[124] = EVT_USER_TRANSACTION_FUNNEL;
    arrayOfSynergyConstants[125] = EVT_USER_MESSAGING_FUNNEL;
    arrayOfSynergyConstants[126] = EVT_USER_SIGNUP_FUNNEL;
    arrayOfSynergyConstants[127] = EVT_USER_GAME_LOAD_FUNNEL;
    arrayOfSynergyConstants[''] = EVT_USER_GAME_DOWNLOAD_FUNNEL;
    arrayOfSynergyConstants[''] = EVT_EVENTS_PURGED;
    arrayOfSynergyConstants[''] = EVT_GP_LEVEL_PROMOTION_DAYS_TOTAL_EAL;
    arrayOfSynergyConstants[''] = EVT_GP_LEVEL_PROMOTION_GAMEPLAY_TIME_TOTAL_EAL;
    arrayOfSynergyConstants[''] = EVT_GP_ACHIEVEMENTS_CHECKPOINTS_EAL;
    arrayOfSynergyConstants[''] = EVT_GP_XPGAIN_EVENT_EAL;
    arrayOfSynergyConstants[''] = EVT_GP_EVENT_USER_EAL;
    arrayOfSynergyConstants[''] = EVT_GP_APP_START_USER_LEVEL_EAL;
    arrayOfSynergyConstants[''] = EVT_EBISU_EMAIL_PROMPT;
    arrayOfSynergyConstants[''] = EVT_EBISU_PROMPT_INPUT;
    arrayOfSynergyConstants[''] = EVT_EBISU_REGISTRATION_FUNNEL;
    arrayOfSynergyConstants[''] = EVT_EBISU_OPTIONAL_REGISTRATION_FIELDS;
    arrayOfSynergyConstants[''] = EVT_EBISU_REGISTRATION_ERROR;
    arrayOfSynergyConstants[''] = EVT_EBISU_SIGNIN_FUNNEL;
    arrayOfSynergyConstants[''] = EVT_EBISU_SIGNIN_ERROR;
    arrayOfSynergyConstants[''] = EVT_EBISU_USER_SIGNIN;
    arrayOfSynergyConstants[''] = EVT_EBISU_USER_FRIENDS_COUNT;
    arrayOfSynergyConstants[''] = EVT_EBISU_ENTER_EBISUUI;
    arrayOfSynergyConstants[''] = EVT_EBISU_FRIENDS_VISIT;
    arrayOfSynergyConstants[''] = EVT_EBISU_FRIEND_SEARCH;
    arrayOfSynergyConstants[''] = EVT_EBISU_FRIEND_INVITE_SENT;
    arrayOfSynergyConstants[''] = EVT_EBISU_FRIEND_INVITE_ACCPTED;
    arrayOfSynergyConstants[''] = EVT_EBISU_NEWSFEED_VISIT;
    arrayOfSynergyConstants[''] = EVT_EBISU_NEWSFEED_TILE_BUTTON_CLICK;
    arrayOfSynergyConstants[''] = EVT_EBISU_NEWSFEED_BANNER_CLICK;
    arrayOfSynergyConstants[''] = EVT_EBISU_NEWSFEED_UPDATES;
    arrayOfSynergyConstants[''] = EVT_EBISU_PROFILE_VISIT;
    arrayOfSynergyConstants[''] = EVT_EBISU_LOGO_YES_CLICK;
    arrayOfSynergyConstants[''] = EVT_EBISU_LOGO_NO_CLICK;
    arrayOfSynergyConstants[''] = EVT_EBISU_RECOVER_PASSWORD_FUNNEL;
    arrayOfSynergyConstants[''] = EVT_EBISU_USER_SIGNOUT;
    arrayOfSynergyConstants[''] = EVT_EBISU_LOAD_FAIL;
    arrayOfSynergyConstants[' '] = EVT_EBISU_FRIEND_PROFILE_BANNER_CLICK;
    arrayOfSynergyConstants['¡'] = EVT_EBISU_FRIEND_PROFILE_GAME_ICON_CLICK;
    arrayOfSynergyConstants['¢'] = EVT_EBISU_FRIEND_INVITE_REJECTED;
    arrayOfSynergyConstants['£'] = EVT_EBISU_PROFILE_BANNER_CLICK;
    arrayOfSynergyConstants['¤'] = EVT_EBISU_PROFILE_GAME_ICON_CLICK;
    arrayOfSynergyConstants['¥'] = EVT_GAME_ERROR_CONNECTIVITY;
    arrayOfSynergyConstants['¦'] = EVT_GAME_ERROR_GAMEPLAY;
    arrayOfSynergyConstants['§'] = EVT_KEYTYPE_NONE;
    arrayOfSynergyConstants['¨'] = EVT_KEYTYPE_GAME_SELLID;
    arrayOfSynergyConstants['©'] = EVT_KEYTYPE_MTX_SELLID;
    arrayOfSynergyConstants['ª'] = EVT_KEYTYPE_MTX_CATEGORY;
    arrayOfSynergyConstants['«'] = EVT_KEYTYPE_SCREEN_NAME;
    arrayOfSynergyConstants['¬'] = EVT_KEYTYPE_EVENT_COUNT;
    arrayOfSynergyConstants['­'] = EVT_KEYTYPE_DURATION;
    arrayOfSynergyConstants['®'] = EVT_KEYTYPE_FREQUENCY;
    arrayOfSynergyConstants['¯'] = EVT_KEYTYPE_FEATURED;
    arrayOfSynergyConstants['°'] = EVT_KEYTYPE_DMG_SECTION;
    arrayOfSynergyConstants['±'] = EVT_KEYTYPE_GAME_PRODUCTID;
    arrayOfSynergyConstants['²'] = EVT_KEYTYPE_DMG_CATEGORY;
    arrayOfSynergyConstants['³'] = EVT_KEYTYPE_SCORE;
    arrayOfSynergyConstants['´'] = EVT_KEYTYPE_ENUMERATION;
    arrayOfSynergyConstants['µ'] = EVT_KEYTYPE_TICKERID;
    arrayOfSynergyConstants['¶'] = EVT_KEYTYPE_BANNERID;
    arrayOfSynergyConstants['·'] = EVT_KEYTYPE_MESSAGEID;
    arrayOfSynergyConstants['¸'] = EVT_KEYTYPE_BANNER_POSITION;
    arrayOfSynergyConstants['¹'] = EVT_KEYTYPE_LANGUAGE;
    arrayOfSynergyConstants['º'] = EVT_KEYTYPE_USER_LEVEL_DATA;
    arrayOfSynergyConstants['»'] = EVT_KEYTYPE_FIELD_ID;
    arrayOfSynergyConstants['¼'] = EVT_KEYTYPE_LOGO_MESSAGE_ID;
    arrayOfSynergyConstants['½'] = EVT_KEYTYPE_FIELD_TYPE;
    arrayOfSynergyConstants['¾'] = EVT_KEYTYPE_SYNERGYID;
    arrayOfSynergyConstants['¿'] = EVT_KEYTYPE_JSON_MAP;
    arrayOfSynergyConstants['À'] = EVT_KEYTYPE_LAST_ENUM;
    $VALUES = arrayOfSynergyConstants;
  }
  
  private SynergyConstants(int paramInt)
  {
    this.value = paramInt;
  }
  
  public static SynergyConstants fromInt(int paramInt)
  {
    for (SynergyConstants localSynergyConstants : ) {
      if (localSynergyConstants.value == paramInt) {
        return localSynergyConstants;
      }
    }
    return EVT_UNDEFINED;
  }
  
  public boolean isSessionEndEventType()
  {
    switch (1.$SwitchMap$com$ea$nimble$tracking$SynergyConstants[ordinal()])
    {
    default: 
      return false;
    }
    return true;
  }
  
  public boolean isSessionStartEventType()
  {
    switch (1.$SwitchMap$com$ea$nimble$tracking$SynergyConstants[ordinal()])
    {
    default: 
      return false;
    }
    return true;
  }
}


/* Location:           E:\Dropbox\Dropbox\RealRacingHack\Decompile\install_dex2jar.jar
 * Qualified Name:     com.ea.nimble.tracking.SynergyConstants
 * JD-Core Version:    0.7.0.1
 */